{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "hello-secret.labels" . | nindent 4 }}
  name: {{ include "hello-secret.fullname" . }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host}}
  {{- end }}
  {{- if .Values.route.tls }}
  tls:
  {{- with .Values.route.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ template "hello-secret.fullname" . }}
{{- end }}
