apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hello-secret
  annotations:
    {{ if .Values.sealedSecrets.scope.namespace }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{ else }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{ end }}
  labels:
    {{- include "hello-secret.labels" . | nindent 4 }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "hello-secret.labels" . | nindent 8 }}
  encryptedData:
    secret: {{ .Values.sealedSecrets.secret }}